### PR TITLE
Fixed #147

### PR DESCRIPTION
**Pull request by pezy**

### CODE REVIEW

**Comment by Mooophy** [comment]
thx guys

**Comment by mudongliang** [comment]
@pezy , will you change file structure of the rest chapters ???
If you do , I will add makefile after you !
If you not , I will add makefile , not wait for you !
It matters the content of makefile !
At Last , I want to add empty main function to test your files , how do you think about it ?

**Comment by pezy** [comment]
> I want to add empty main function to test your files , how do you think about it ?

You can add it as you want.

> will you change file structure of the rest chapters ???

Yes. 

Thx for your contribution.

**Comment by mudongliang** [comment]
OK !

2015-03-07 19:26 GMT+08:00 pezy <notifications@github.com>:

**Pull request merged**
