### PR TITLE
fix the potential problem for copy assignment operator

### PR DESCRIPTION
**Pull request by Soyn**
1. Before the assignment starts, we need to check the right hand size value is the same with left or not.
2. Memory allocation failed should be considered. My solution is exception safety.

### CODE REVIEW

**Comment by pezy** [comment]
> Before the assignment starts, we need to check the right hand size value is the same with left or not.
 
agree

> Memory allocation failed should be considered. My solution is exception safety.

why?

**Comment by Soyn** [comment]
In your solution if the allocation failed. The `new_ps` will be nullptr. But the rest of statements still execute. The `ps` was deleted.And this is not the result will expect(i.e. we need to keep the original instance safe if the exception occurs). In my solution, I use the copy constructor to create a temp object. If failed, the `bad_alloc` will be thrown. The original state will not be modified(That's all we expect). There is a more clearer explanation from stacl overflow. [c++ assignment operator exception safety](http://stackoverflow.com/questions/31460048/c-assignment-operator-exception-safety)

And I get this idea from <<剑指offer>>.

**Comment by pezy** [comment]
> In my solution, I use the copy constructor to create a temp object. If failed, the bad_alloc will be thrown. The original state will not be modified(That's all we expect).

```cpp
std::string *new_ps = new std::string(*hp.ps);
```

If this statement failed, the `bad_alloc` would also thrown. and following code (like `delete ps;`) couldn't be executed. So why the original state would be modified?

-----

> And I get this idea from <<剑指offer>>.

We called this as [copy-and-swap idiom](http://stackoverflow.com/questions/3279543/what-is-the-copy-and-swap-idiom), and the book would talk about this after 13.3. Thus, I don't think it's a good idea to show this idiom in 13.1's exercise.

-----

Additionally, the solution of this exercise is consistent with the example code of the book(13.2.1. Classes That Act Like Values):

```cpp
HasPtr& HasPtr::operator=(const HasPtr &rhs)
{
    auto newp = new string(*rhs.ps); // copy the underlying string
    delete ps; // free the old memory
    ps = newp; // copy data from rhs into this object
    i = rhs.i;
    return *this; // return this object
}
```

FYI.

**Comment by Soyn** [comment]
Agreed. I will close this. And I will push another pull request for checking the rhs and lhs is same or not. Can I?

**Comment by pezy** [comment]
@Soyn Of course, thx.

**Pull request closed without merging**
