### PR TITLE
Revise makefile

### PR DESCRIPTION
**Pull request by mudongliang**
change makefile to work with the current file structure, and report some problems in the makefile !

### CODE REVIEW

**Comment by mudongliang** [comment]
@pezy , I find some problems in your change about ch13 , 
#	ex13_48 : can not compile successfully!
+#	ex13_28 ex13_26 ex13_18 ex13_34_36_37 ex13_44_47 ex13_53 : no main function!  
+#	ex13_42_StrVec ex13_49_Message ex13_49_String ex13_49_StrVec : no main function! 
+#	ex13_39 ex13_40 : no StrVec.h and correspending header file is useless!

**Comment by mudongliang** [comment]
ex13_42_StrVec is used for ex13_42_TextQuery , it is not included!

**Comment by Mooophy** [comment]
thx

**Comment by pezy** [comment]
> ex13_48 : can not compile successfully!

should comply with *ex13_44_47.h* and *ex13_44_47.cpp*

> ex13_28 ex13_26 ex13_18 ex13_34_36_37 ex13_44_47 ex13_53 : no main function!
> 
> +# ex13_42_StrVec ex13_49_Message ex13_49_String ex13_49_StrVec : no main function!

Yup, just support class for the question.

> ex13_39 ex13_40 : no StrVec.h and correspending header file is useless!

Sorry, my mistake, I will fix it as soon as possible. Thx a lot for reporting. :smile_cat:

**Comment by mudongliang** [comment]
@pezy , are ex13_49_Message ex13_49_String ex13_49_StrVec related or unrelated ?
And are they just the content of class ???
Will you compile those files into ex13_49 like ex13_42 ???

**Comment by pezy** [comment]
> are ex13_49_Message ex13_49_String ex13_49_StrVec related or unrelated ?

Unrelated.

> And are they just the content of class ???

Yup.

> Will you compile those files into ex13_49 like ex13_42 ???

No. 
> Exercise 13.42:
>**Test** your StrVec class by using it...
>
>-----
>
> Exercise 13.49:
>Add a move constructor and move-assignment operator to ...

Thus, *13.42* should test by main function, but *13.49* don't need.

However, you can added it if you feel it is necessary.  :ghost:

**Pull request merged**
