### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by h1arshad**
wrong answer

### CODE REVIEW

**Comment by pezy** [comment]
@h1arshad  why? `int calc(const int, const int)` is the redefinition of `int calc(int, int)`, is it? :question:

**Comment by Mooophy** [comment]
@h1arshad 
Can you state why the original answer is wrong?

**Comment by h1arshad** [comment]
I rechecked it. My bad I was wrong. I made a declaration not a definition for it

**Comment by Mooophy** [comment]
@h1arshad No worries.

**Pull request closed without merging**
