### PR TITLE
fixed a serious bug may cause an infinite loop.

### PR DESCRIPTION
**Pull request by XDXX**
The current version has a serious bug which may cause an infinite loop.This bug will appear  when the oldVal is a substring of the newVal(eg: oldVal = "tho", newVal = "tthough").
What's more, the exercise requires using iterators but the current version doesn't using any iterators.
My version is tested in Visual Studio 2013.But it can't pass the compilation in gcc 4.9.2 because gcc 4.9.2 doesn't support the c++11 feature "iterator insert (iterator p, InputIterator first, InputIterator last);".

### CODE REVIEW

**Comment by Mooophy** [comment]
Hi @XDXX Thx for contribution. 
After reading your PR, two things we can talk about.
 * Can you add a comment in to this code, explicitly showing that it doesn't compile on GCC, please use VS or Clang instead?
 * Why the reference symbols in the function signature have been deleted?
```cpp
void func(string &s, const string &oldVal, const string &newVal)
```

**Comment by XDXX** [comment]
I will add some comments in my code.As for the deleting of reference symbols, I assumed that the length of oldVal or newVal is short.But now I think it is better using the reference symbols.So I will also add the reference symbols in my code.

**Comment by Mooophy** [comment]
awesome

**Comment by pezy** [comment]
> gcc 4.9.2 doesn't support the c++11 feature "iterator insert (iterator p, InputIterator first, InputIterator last);".

@XDXX Agree. I ask this problem on SO: http://stackoverflow.com/questions/29690369 to confirm it. FYI.

However, some guys like @mudongliang who always using gcc, may be disappointed. They can't find the answer for themselves. How to solve this problem?

**Comment by pezy** [comment]
I am trying to make our solution cross-platform, for reference purposes only:

```cpp
void func(string &s, string const& oldVal, string const& newVal)
{
	for (auto iter = s.begin(); std::next(iter, oldVal.size()) != s.end();)
		if (*iter == oldVal[0] && string(iter, std::next(iter, oldVal.size())) == oldVal) {
			iter = s.erase(iter, std::next(iter, oldVal.size()));
			size_t pos = std::distance(s.begin(), iter) + newVal.size();
			s.insert(iter, newVal.begin(), newVal.end());
			iter = std::next(s.begin(), pos);
		}
		else  ++iter;
}
```

How about this?

**Comment by XDXX** [comment]
This version also has a serious bug which may cause Memory Overflow.The bug will appear when the string was reallocated.
Try s="my world is a big world.", oldVal = "world", newVal = "worldwwwwwwwwwwwwww"

**Comment by XDXX** [comment]
@pezy

**Comment by pezy** [comment]
@XDXX sorry for the bug. thx a lot.

```cpp
void func(string &s, string const& oldVal, string const& newVal)
{
	for (auto iter = s.begin(); std::distance(iter, s.end()) > static_cast<ptrdiff_t>(oldVal.size()); )
        if (*iter == oldVal[0] && string(iter, std::next(iter, oldVal.size())) == oldVal) {
            iter = s.erase(iter, std::next(iter, oldVal.size()));
            size_t pos = std::distance(s.begin(), iter) + newVal.size();
            s.insert(iter, newVal.begin(), newVal.end());
            iter = std::next(s.begin(), pos);
        } else  ++iter;
}
```

any other bugs?

**Comment by XDXX** [comment]
@pezy 
The function is perfect now.I recommend that we should provided two answers for this exercise.One for the purpose of using the c++11's features and one for the purpose of cross-platform.By the way,Do you mind if I change my codes style for the consistency?
ps:My English ability is limited.Please don't mind it.

**Comment by pezy** [comment]
Don't worry about English.

Just change it as you wish. then, I will merge it into master branch.

thx for your contribution.

**Comment by XDXX** [comment]
@pezy 
I found there is a little bug in your codes.
std::distance(iter, s.end())  >  static_cast<ptrdiff_t>(oldVal.size()) in your code should be
std::distance(iter, s.end())  >= static_cast<ptrdiff_t>(oldVal.size())
Otherwise, the last word of string equals oldVal won't be replace with newVal.
e.g. s = "my world is a big world", oleVal = "world", newVal = "life". 
result:s = "my life is a big world".
I will fixed it in next commit.

**Comment by XDXX** [comment]
I changed the file name of ex9_43.cpp to ex9_43_1.cpp and adding a new file ex9_43_2.cpp.But I didn't modify the README.md file.I hope someone could modify the README.md so that it can work well.

**Comment by pezy** [comment]
Thx a lot

**Comment by XDXX** [comment]
My pleasure :-)

**Comment by zyxhangzhou** [comment]
The GCC version I used is GCC 7.2.0, which would not cause that problem. (By the way, I'm another guy using the same avatar coincidentally : )

**Pull request merged**
