### PR TITLE
6.39(a) change to 'legal'

### PR DESCRIPTION
**Pull request by PwzXxm**
int calc(int, int);
int calc(const int, const int);
Legal. Top-level const is ignored.

### CODE REVIEW

**Comment by pezy** [comment]
see the reason in #633.

**Comment by PwzXxm** [comment]
I was thinking it is legal to declare but it is illegal to call. Since declarations like so can be compiled without error.

image

**Comment by pezy** [comment]
@PwzXxm I agree with you. But it is same as:

```cpp
#include <iostream>

int calc(int a, int b);
int calc(int a, int b);

int main() {
    return 0;
};
```

It can be also compiled without error, but meaningless... 

After all, you are right. I will merge it later... thx

**Comment by PwzXxm** [comment]
Yep, meaningless lol. Sorry for the unclear expressions at the start. Thx.  : )

**Pull request merged**
