### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wxfil**

### CODE REVIEW

**Comment by wxfil** [comment]
.

**Comment by pezy** [comment]
@wxfil 

`p3` is a const pointer, cannot assign again. check following:

```cpp
int main()
{
    int i = 0;
    const int ic = 2; 
    const int *const p3 = &i;
    p3 = &ic; // error. Cannot assign to readonly type `int const * const`
}
```

**Comment by Mooophy** [comment]
Agree with @pezy

**Comment by Mooophy** [comment]
Remember to close this PR, when no more discussion is needed.
@pezy  @wxfil

**Pull request closed without merging**
