### PR TITLE
fixed #136

### LINKED ISSUE #136: Exercise 9.34
这一题的代码中用到了9.32中已经证明是illegal的语句`iter = vi.insert(iter, *iter++);`，似乎不太妥当。

### PR DESCRIPTION
**Pull request by pezy**

### CODE REVIEW

**Comment by Mooophy** [comment]
So quick.........

**Comment by Mooophy** [comment]
@lafener 
Can you make a double check to make sure every thing right?

**Comment by lafener** [comment]
@Mooophy 
https://github.com/Mooophy/Cpp-Primer/blob/master/ch09/ex9_34.cpp 是这个吗？我看到的已经没问题了

**Comment by Mooophy** [comment]
Yup

**Pull request merged**
