### PR TITLE
fix Ex12.19~Ex12.20

### PR DESCRIPTION
**Pull request by Soyn**
In Ex12.20 you included the "Ex12.19.h",but there is a problem you use the begin() and end(),but the defination of them are in Ex12.19.cpp,And you do it in Ex12.20 in the same way.So I delete the Ex.12.19.cpp.And add the function defination in Ex12.19.h.And i test it in Ex12.20.cpp.It works well.

### CODE REVIEW

**Comment by pezy** [comment]
:sweat: 

Please compile ex12_20.cpp in this way:

```sh
g++ ex12_20.cpp ex12_19.cpp -std=c++11
```

Implementation codes in headers is generally a bad idea since it forces recompilation of all files that includes the header when you change the actual code rather than the declarations. It will also slow down compilation since you'll need to parse the code in every file that includes the header.

A reason to have code in header files is that it's generally needed for the keyword **`inline`** to work properly and when using templates that's being instanced in other `.cpp` files.

**Comment by Soyn** [comment]
Oh,I don't know this usage.And i can't understand this "A reason to have code in header files is that it's generally needed for the keyword inline to work properly and when using templates that's being instanced in other .cpp files."Can you explain this in Chinese.Thx

**Comment by pezy** [comment]
@Soyn 

把实现代码放到头文件里，通常有两个理由：

1. inline 成员
2. 模板

除此之外，尽量不要这么干。

**Comment by Soyn** [comment]
Thx for your patience

**Pull request closed without merging**
