### PR TITLE
fix

### PR DESCRIPTION
**Pull request by Soyn**
Ex 9.45 ask us to use iterator,but your solution didn't follow it.And i think i fix it.Please check it,thank you.
ps:You can visit this page to konw the usage of insert.
http://www.cplusplus.com/reference/string/string/insert/

### CODE REVIEW

**Comment by pezy** [comment]
@Soyn Sorry, your pull request can't be merged automatically. please syncing first.

In addition, Ex 9.45 have bug exactly, the old version is all right, seem to be my merge fault. I would be correct it later. thx for your reporting. :bow:

**Comment by Soyn** [comment]
不能merged是什么意思，用github没多久，求指教，谢谢

**Comment by pezy** [comment]
@Soyn Like this:

image

Maybe you should [syncing](https://help.github.com/articles/syncing-a-fork/) first.

**Comment by Soyn** [comment]
我用的 github for windows客户端，我在客户端上已经显示同步了，另外为什么要用inline函数呢？

**Comment by pezy** [comment]
@Soyn 

1. Syncing with this repo, rather than yourself (as your client show).
2. Probably for some compilers `inline` function can improve the performance for such short function.

**Comment by Soyn** [comment]
我去查查文档吧，谢谢了，但是我觉得在这里用inline没有必要

**Pull request closed without merging**
