### PR TITLE
changed to use integral comparison

### PR DESCRIPTION
**Pull request by Little-Meow**
When comparing string sizes, it's better to use an integral value as the compiler/machine -may- take alphabetical order into account over actual string length. depending on several factors. Additionally, we're specifically working with lengths so it's nice to have them presented as such for context, clarity and other comparisons.

### CODE REVIEW

**Comment by Mooophy** [comment]
Please check description for this exercise :
>Exercise 5.19: Write a program that uses a do while loop to repetitively
request two strings from the user and report which string is **less than**
the other.

IMHO it asked to compare two `string`s directly, rather than comparing by `size()`.

**Comment by Little-Meow** [comment]
> IMHO it asked to compare two `strings` directly, rather than comparing by `size()`.

To me the '**less than**' indicates size, which is better presented as a real number (And given the potential side effects, the user may adapt/modify the solution and become confused by incorrect output!)

**Comment by Mooophy** [comment]
I know it's a little bit wired at first glance. But please trust me it's referring to `comparing directly`. After reading later parts especially chapter 14, you would understand what's going on more naturally. 

Closing.

**Comment by Little-Meow** [comment]
I haven't read the book, but I'll take your word. I understand how string comparison works, but in some cases it will not work as expected in this context.

Removed branch.

**Pull request closed without merging**
