### PR TITLE
Update ex11_23.cpp

### PR DESCRIPTION
**Pull request by miaojiuchen**
it seems that should use multimap<string,vector<string>> instead of multimap<string,string> here

### CODE REVIEW

**Comment by pezy** [comment]
> Exercise 11.23: 
> Rewrite the map that stored vectors of children’s names with a key that is the family last name for the exercises in § 11.2.1 (p. 424) **to use a `multimap`.**

please notice the question.

**Comment by Mooophy** [comment]
Agree with @pezy 
Please make a double check @miaojiuchen , Thx.

**Comment by miaojiuchen** [comment]
oh sorry...i didn't get it very well  Thx! :)

**Comment by Mooophy** [comment]
No worries. Please close this PR, if no more discussion needed. 
Thx.

**Pull request closed without merging**
