### PR TITLE
update ex14_43.cpp

### PR DESCRIPTION
**Pull request by XDXX**
fixed ex14_43

### CODE REVIEW

**Comment by Mooophy** [comment]
Thx @XDXX 

While reviewing this PR, which worked pretty well, I came up with another way for this exercise:
```cpp
#include <iostream>
#include <string>
#include <functional>
#include <algorithm>

int main()
{
    auto data = { 2, 3, 4, 5 };
    int input;
    std::cin >> input;
    std::modulus<int> mod;
    auto predicator = [&](int i){ return 0 == mod(input, i); };
    auto is_divisible = std::any_of(data.begin(), data.end(), predicator);
    std::cout << (is_divisible ? "Yes!" : "No!") << std::endl;

    return 0;
}
```

Since this section is talking about `<functional>`, I guess this way looks more functional. What's your opinion?

**Comment by XDXX** [comment]
@Mooophy 
I think your idea is good but there is a little bug in your code.
You should use `std::all_of` instead of the `std::any_of`. Because the exercise says "**any element** in
a container".

**Comment by Mooophy** [comment]
I don't think so.
`std::any_of` for  " **any** element in a container".
`std::all_of` for " **all** elements in a container".

**Comment by Mooophy** [comment]
**any** here means 任一 in Chinese， rather than 所有、全部。

**Comment by XDXX** [comment]
@Mooophy 
I have both Chinese version and English version of this book.
In Chinese version it says "容器中的所有元素".

**Comment by Mooophy** [comment]
If so , I believe it's a bug made in in translation.

**Comment by Mooophy** [comment]
It's not the first bug I come across in the Chinese Version.

**Comment by XDXX** [comment]
In this case, your code is perfect.

**Pull request merged**
