### PR TITLE
Update ex12_23.cpp

### PR DESCRIPTION
**Pull request by MainasuK**
C++ Primer 第5版 中文版中原题如下：
练习 12.23：编写一个程序，连接两个字符串字面量，将结果保存在一个动态分配的 char 数组中。重写这个程序，连接两个标准库 string 对象。

在 strlen() 里用到了 C 中字符串字面量在编译时隐式连接的特性。

### CODE REVIEW

**Comment by Mooophy** [comment]
For the first modification:
```cpp
char *concatenate_string = new char[strlen("hello " "world") + 1]();
```
Can you list the reasons why this way is better?

For the second:
```cpp
char *concatenate_string2 = new char[str1.length() + str2.length() + 1]();
strcpy(concatenate_string2, (str1+str2).c_str());
std::cout << concatenate_string2 << std::endl;
```
Why do think it's better than:
```
std::cout << str1 + str2 << std::endl;
```

**Comment by MainasuK** [comment]
OK.
This exercise is just after the section, 12.2 动态数组. So we can use a integer to init a array.
e.g.
    int *p = new int[get_size()]();

Then, of course you can concatenate two strings with '+' and output it by cout.
However it's not the correct answer of this exercise (a.k.a save the concatenated string in dynamically allocated array).

Finally, We can save the memory If we use strlen() or get_size or something to create a dynamically array. The 255 is not always right.

**Comment by Mooophy** [comment]
Um, agree with you for the first one. As for the second, I'd like to keep the current implementation. Can you propose pull request for the first one only?

**Comment by MainasuK** [comment]
Sure, it's your right. I've discarded the second.
And I stick to my opinion. XD

**Comment by Mooophy** [comment]
Thx.

**Pull request merged**
