### PR TITLE
One change.

### PR DESCRIPTION
**Pull request by smileqiao1988**
Thank you for making this awesome answer book. Just made a little change. Please review.

### CODE REVIEW

**Comment by Mooophy** [comment]
Please indent this code correctly.

**Comment by smileqiao1988** [comment]
Already indented the code. Please review. Thx.

**Comment by Mooophy** [comment]
Thx for it @smileqiao1988 .

But to be honest..a few problems still linger there..

*  `a` is a bad variable name, please avoid such thing.
* `a` and `result` should be declared as the same type.
*  Keep variable declaration as close to its use as possible.(For example the variable `result`) 
* Expression `a>=0` will always be `true`, as it's a `unsigned int`. 
* Please remove unnecessary syntax noises like `{ }`
 
Do you mind making a double check?
You know we are attempting to improve some cool guy's code. If I merge your pull request too boldly, I'm afarid Mr @pezy would frown on me...

FYI, the code below can be used as a reference.
```cpp
#include <iostream>
#include <string>

using std::string;
using std::cin;
using std::cout;
using std::endl;

void factorial(){
	unsigned num = 0;
	cout << "Please input a positive number: " << endl;
	cin >> num;
	cout << num;

	unsigned result = 1;
	if (num <= 33){
		while (num >= 1)
			result *= num--;
		cout << "!= " << result << endl;
	}
	else
		cout << " is out of range." << endl;
}

int main() {
	factorial();
	return 0;
}
```

**Comment by pezy** [comment]
Thanks @Mooophy 's effort.

1. Just wonder about the meaning of magic number `33`. why it is the range?
2. `!=`, look like **unequal**. The output such as `0!= 1` will causing some guy to be puzzled...

some advice about this issue. please don't mind.  :ghost:

**Comment by Mooophy** [comment]
@smileqiao1988 
@pezy and I carried out experiments to check the threshold for input. Below is what we got.
```java
...
0!  =  1
1!  =  1
2!  =  2
3!  =  6
4!  =  24
5!  =  120
6!  =  720
7!  =  5040
8!  =  40320
9!  =  362880
10!  =  3628800
11!  =  39916800
12!  =  479001600     <-- threshold for unsigned int
13!  =  6227020800    <-- overflow
14!  =  87178291200
15!  =  1307674368000
16!  =  20922789888000
17!  =  355687428096000
18!  =  6402373705728000
19!  =  121645100408832000
20!  =  2432902008176640000
21!  =  51090942171709440000
22!  =  1124000727777607680000
23!  =  25852016738884976640000
24!  =  620448401733239439360000
25!  =  15511210043330985984000000
26!  =  403291461126605635584000000
27!  =  10888869450418352160768000000
28!  =  304888344611713860501504000000
29!  =  8841761993739701954543616000000
30!  =  265252859812191058636308480000000
31!  =  8222838654177922817725562880000000
32!  =  263130836933693530167218012160000000
33!  =  8683317618811886495518194401280000000
34!  =  295232799039604140847618609643520000000
```

Since the range for a `unsigned int` is something like : `0 to 4,294,967,295`, `12` seems a good choice , 33 is just too big.

**Comment by mudongliang** [comment]
Agree with @Mooophy !
When we are programming , we should notice all kinds of safety , for example , integer overflow above!
I am learning Information Security at school!

**Comment by smileqiao1988** [comment]
@Mooophy Thank you for your nice suggestions. You are right. I do need to be aware of variable identifier's problem. That is a bad habit of me. :) 
For the code, I did more modifications, please review.
But I still declared "num" as int for two reasons.
1. If not, the output will always be "0! is 1", when the input "num" is negative. 
2. Input "num" is much more smaller than result. So no worry about the overflow problem.

Thank you again for doing the real calculation. When I was running my old code, I didn't really check if output is correct. P.S. I like that you said "cool guys' code" lol. Please let me know if there are other problems in this code.

**Comment by Mooophy** [comment]
Perfect!

**Comment by smileqiao1988** [comment]
@pezy For the magic 33, I have to say it is a big fault of me. But the reason is that for input bigger than 33, the output is "num! is 0". I just assumed that it is a correct output whenever I saw a positive output lol. I should not avoid the dirty work later. So now it is magic 12.

And I changed the output form from "1!=1" to "1! is 1". Hope this can solve your concern.

Please don't hesitate to give me suggestions. And according to Mooophy's word, you are the cool guy. Please don't frown on Mooophy. Just throw wrong code on my face lol. Thanks for your guys' awesome work.

**Comment by smileqiao1988** [comment]
@mudongliang Information Security!! sounds awesome lol. I am agree with ur idea too. That is why I put a range over there. But a wrong range in the previous version lol.

**Pull request merged**
